/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedApiDemoRouteImport } from './routes/_authed/api-demo'
import { Route as AuthedDocumentIndexRouteImport } from './routes/_authed/document/index'

import { Route as rootRoute } from './routes/__root'
import { Route as AuthedImport } from './routes/_authed'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AuthedIndexImport } from './routes/_authed/index'
import { Route as AuthedSlideSlideIdImport } from './routes/_authed/slide.$slideId'

// Create/Update Routes

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApiDemoRoute = AuthedApiDemoRouteImport.update({
  id: '/api-demo',
  path: '/api-demo',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocumentIndexRoute = AuthedDocumentIndexRouteImport.update({
  id: '/document/',
  path: '/document/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedSlideSlideIdRoute = AuthedSlideSlideIdImport.update({
  id: '/slide/$slideId',
  path: '/slide/$slideId',
  getParentRoute: () => AuthedRoute,
} as any)

// Populate the FileRoutesByPath interface
export interface FileRoutesByFullPath {
  '/api-demo': typeof AuthedApiDemoRoute
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginIndexRoute
  '/document': typeof AuthedDocumentIndexRoute
}
export interface FileRoutesByTo {
  '/api-demo': typeof AuthedApiDemoRoute
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginIndexRoute
  '/document': typeof AuthedDocumentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/api-demo': typeof AuthedApiDemoRoute
  '/_authed/': typeof AuthedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authed/document/': typeof AuthedDocumentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api-demo' | '/' | '/login' | '/document'
  fileRoutesByTo: FileRoutesByTo
  to: '/api-demo' | '/' | '/login' | '/document'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/api-demo'
    | '/_authed/'
    | '/login/'
    | '/_authed/document/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/api-demo': {
      id: '/_authed/api-demo'
      path: '/api-demo'
      fullPath: '/api-demo'
      preLoaderRoute: typeof AuthedApiDemoRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/document/': {
      id: '/_authed/document/'
      path: '/document'
      fullPath: '/document'
      preLoaderRoute: typeof AuthedDocumentIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/slide/$slideId': {
      id: '/_authed/slide/$slideId'
      path: '/slide/$slideId'
      fullPath: '/slide/$slideId'
      preLoaderRoute: typeof AuthedSlideSlideIdImport
      parentRoute: typeof AuthedImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedApiDemoRoute: typeof AuthedApiDemoRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedSlideSlideIdRoute: typeof AuthedSlideSlideIdRoute
  AuthedDocumentIndexRoute: typeof AuthedDocumentIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedApiDemoRoute: AuthedApiDemoRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedSlideSlideIdRoute: AuthedSlideSlideIdRoute,
  AuthedDocumentIndexRoute: AuthedDocumentIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthedRouteWithChildren
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginIndexRoute
  '/slide/$slideId': typeof AuthedSlideSlideIdRoute
}

export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginIndexRoute
  '/slide/$slideId': typeof AuthedSlideSlideIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authed/slide/$slideId': typeof AuthedSlideSlideIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/login' | '/slide/$slideId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/slide/$slideId'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/'
    | '/login/'
    | '/_authed/slide/$slideId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authed",
        "/login/"
      ]
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/",
        "/_authed/slide/$slideId"
      ]
    },
    "/_authed/": {
      "filePath": "_authed/index.tsx",
      "parent": "/_authed"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/_authed/slide/$slideId": {
      "filePath": "_authed/slide.$slideId.tsx",
      "parent": "/_authed"
    }
  }
}
ROUTE_MANIFEST_END */
