services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:stable-v1.31-9900730
    ports:
      - "8090:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-transformers
      - ENABLE_MODULES=text2vec-transformers
      - CLUSTER_HOSTNAME=node1
      - TRANSFORMERS_INFERENCE_API=http://transformers:8080
    volumes:
      - weaviate_data:/var/lib/weaviate

  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=document_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  transformers:
    image: semitechnologies/transformers-inference:cpu-2.4.0
    environment:
      - MODEL_NAME=sentence-transformers/all-MiniLM-L6-v2
      - NUM_THREADS=4
    networks:
      - spring-cloud-network

volumes:
  weaviate_data:
  minio_data:
  postgres_data:
