host: nemo.student.k8s.aet.cit.tum.de

services:
  - name: client
    servicePort: 80
    containerPort: 80
    path: /
    image: ghcr.io/aet-devops25/team-sigma/client:latest
  - name: api-gateway
    servicePort: 80
    containerPort: 80
    path: /api
    image: ghcr.io/aet-devops25/team-sigma/api-gateway:latest
    env:
      - name: SPRING_APPLICATION_NAME
        value: api-gateway
      - name: SERVER_PORT
        value: "80"
      - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://eureka:8761/eureka/
  - name: eureka
    servicePort: 8761
    containerPort: 8761
    image: ghcr.io/aet-devops25/team-sigma/eureka:latest
    env:
      - name: SPRING_APPLICATION_NAME
        value: eureka
      - name: SERVER_PORT
        value: "8761"
      - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
        value: "false"
      - name: EUREKA_CLIENT_FETCH_REGISTRY
        value: "false"
  - name: document-service
    servicePort: 80
    containerPort: 80
    image: ghcr.io/aet-devops25/team-sigma/document-service:latest
    env:
      - name: SPRING_APPLICATION_NAME
        value: document-service
      - name: SERVER_PORT
        value: "80"
      - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://eureka:8761/eureka/
      - name: WEAVIATE_URL
        value: weaviate:8080
      - name: MINIO_URL
        value: http://minio:9000
      - name: MINIO_ACCESS_KEY
        value: minioadmin
      - name: MINIO_SECRET_KEY
        value: minioadmin
      - name: POSTGRES_HOST
        value: postgres
      - name: POSTGRES_PORT
        value: "5432"
      - name: POSTGRES_DB
        value: document_db
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: openai-secret
            key: api-key
  - name: chat-service
    servicePort: 80
    containerPort: 80
    image: ghcr.io/aet-devops25/team-sigma/chat-service:latest
    env:
      - name: ENVIRONMENT
        value: docker
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: openai-secret
            key: api-key
  - name: summary-service
    servicePort: 80
    containerPort: 80
    image: ghcr.io/aet-devops25/team-sigma/summary-service:latest
    env:
      - name: ENVIRONMENT
        value: docker
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: openai-secret
            key: api-key
  - name: lecture-service
    servicePort: 80
    containerPort: 80
    image: ghcr.io/aet-devops25/team-sigma/lecture-service:latest
    env:
      - name: SPRING_APPLICATION_NAME
        value: lecture-service
      - name: SERVER_PORT
        value: "80"
      - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://eureka:8761/eureka/
      - name: POSTGRES_HOST
        value: postgres
      - name: POSTGRES_PORT
        value: "5432"
      - name: POSTGRES_DB
        value: lecture_db
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
  - name: weaviate
    servicePort: 8080
    containerPort: 8080
    image: cr.weaviate.io/semitechnologies/weaviate:stable-v1.31-9900730
    env:
      - name: QUERY_DEFAULTS_LIMIT
        value: "25"
      - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
        value: "true"
      - name: PERSISTENCE_DATA_PATH
        value: /var/lib/weaviate
      - name: DEFAULT_VECTORIZER_MODULE
        value: text2vec-openai
      - name: ENABLE_MODULES
        value: text2vec-openai,generative-openai
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: openai-secret
            key: api-key
      - name: OPENAI_APIKEY
        valueFrom:
          secretKeyRef:
            name: openai-secret
            key: api-key
      - name: CLUSTER_HOSTNAME
        value: node1
  - name: minio
    servicePort: 9000
    containerPort: 9000
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    command:
      - server
    args:
      - /data
    env:
      - name: MINIO_ROOT_USER
        value: minioadmin
      - name: MINIO_ROOT_PASSWORD
        value: minioadmin
      - name: MINIO_PROMETHEUS_AUTH_TYPE
        value: public
  - name: postgres
    servicePort: 5432
    containerPort: 5432
    image: postgres:15-alpine
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
      - name: POSTGRES_DB
        value: postgres
  - name: prometheus
    servicePort: 9090
    containerPort: 9090
    image: prom/prometheus:latest
  - name: grafana
    servicePort: 3000
    containerPort: 3000
    image: grafana/grafana:latest
    env:
      - name: GF_SECURITY_ADMIN_PASSWORD
        value: admin
      - name: GF_USERS_ALLOW_SIGN_UP
        value: "false"
      - name: GF_LOG_LEVEL
        value: error
