image:
  repository: ghcr.io/aet-devops25/team-sigma
  tag: latest

host: nemo.student.k8s.aet.cit.tum.de

services:
  - name: client
    targetPort: 3000
    path: /
  - name: api-gateway
    targetPort: 8080
    path: /api
  - name: eureka
    targetPort: 8761
  - name: hello-service
    targetPort: 8080
  - name: document-service
    targetPort: 8080
