import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./api"; // generated by openapi-typescript

// Create the fetch client with type safety
const fetchClient = createFetchClient<paths>({
  baseUrl: "http://localhost:8080",
});

// Create the React Query client
export const $api = createClient(fetchClient);

// Export the fetch client for direct use if needed
export { fetchClient };

// Export types for external use
export type ApiPaths = paths; 