apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: team-sigma
  labels:
    app: api-gateway
    component: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        component: gateway
    spec:
      containers:
        - name: api-gateway
          image: team-sigma/api-gateway:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_APPLICATION_NAME
              value: "api-gateway"
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka:8761/eureka/"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      initContainers:
        - name: wait-for-eureka
          image: busybox:1.35
          command:
            [
              "sh",
              "-c",
              "until nc -z eureka 8761; do echo waiting for eureka; sleep 2; done;",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: team-sigma
  labels:
    app: api-gateway
    component: gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
