apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --build local -v -f ../docker-compose.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --build local -v -f ../docker-compose.yaml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: client
    spec:
      containers:
        - image: client
          name: client
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
