apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: team-sigma
  labels:
    app: eureka
    component: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
        component: service-discovery
    spec:
      containers:
        - name: eureka
          image: team-sigma/eureka:latest
          ports:
            - containerPort: 8761
              name: http
          env:
            - name: SPRING_APPLICATION_NAME
              value: "eureka"
            - name: SERVER_PORT
              value: "8761"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: team-sigma
  labels:
    app: eureka
    component: service-discovery
spec:
  selector:
    app: eureka
  ports:
    - name: http
      port: 8761
      targetPort: 8761
      protocol: TCP
  type: ClusterIP
