apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --build local -v -f ../docker-compose.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: hello-service
  name: hello-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hello-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --build local -v -f ../docker-compose.yaml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: hello-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8761/eureka/
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_APPLICATION_NAME
              value: hello-service
          image: hello-service
          name: hello-service
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
