apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
  namespace: team-sigma
  labels:
    app: hello-service
    component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      labels:
        app: hello-service
        component: microservice
    spec:
      containers:
        - name: hello-service
          image: team-sigma/hello-service:latest
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: SPRING_APPLICATION_NAME
              value: "hello-service"
            - name: SERVER_PORT
              value: "8081"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka:8761/eureka/"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      initContainers:
        - name: wait-for-eureka
          image: busybox:1.35
          command:
            [
              "sh",
              "-c",
              "until nc -z eureka 8761; do echo waiting for eureka; sleep 2; done;",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: team-sigma
  labels:
    app: hello-service
    component: microservice
spec:
  selector:
    app: hello-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
