spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api-gateway}

  cloud:
    gateway:
      routes:
        - id: document-service-api
          uri: http://document-service:8080
          predicates:
            - Path=/api/documents/**, /api/documents
          filters:
            # Preserve the full path so that "/api/documents" reaches the backend unmodified
            - StripPrefix=0
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
              - "HEAD"
            allowedHeaders:
              - "*"
            allowCredentials: false

server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: "API Gateway"
        primaryName: "API Gateway"
      - url: /api/document/v3/api-docs
        name: "Document Service"
        primaryName: "Document Service"
      - url: /api/hello/v3/api-docs
        name: "Hello Service"
        primaryName: "Hello Service"
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: "gateway"
      paths-to-match: "/api/gateway/**"
      packages-to-scan: "de.tum.team_sigma.api_gateway"
    - group: "full"
      paths-to-match: "/**"
      packages-to-scan: "de.tum.team_sigma.api_gateway"
