apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  create-multiple-databases.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        -- Create databases for services that need persistent storage
        CREATE DATABASE lecture_db;
        CREATE DATABASE document_db;
        
        -- Grant privileges to the default user
        GRANT ALL PRIVILEGES ON DATABASE lecture_db TO $POSTGRES_USER;
        GRANT ALL PRIVILEGES ON DATABASE document_db TO $POSTGRES_USER;
    EOSQL

    echo "Multiple databases created successfully!"
