{{- range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        imagePullPolicy: Always
        ports:
        {{- range .ports }}
        - containerPort: {{ .containerPort }}
          {{- if .name }}
          name: {{ .name }}
          {{- end }}
          {{- if .protocol }}
          protocol: {{ .protocol }}
          {{- end }}
        {{- end }}
        {{- if .command }}
        command:
          {{- range .command }}
          - {{ . }}
          {{- end }}
        {{- end }}
        {{- if .args }}
        args:
          {{- range .args }}
          - {{ . }}
          {{- end }}
        {{- end }}
        {{- if .env }}
        env:
        {{- range .env }}
        - name: {{ .name }}
          {{- if .value }}
          value: {{ .value | quote }}
          {{- else if .valueFrom }}
          valueFrom:
            {{- if .valueFrom.secretKeyRef }}
            secretKeyRef:
              name: {{ .valueFrom.secretKeyRef.name }}
              key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}
        {{- if .volumeMounts }}
        volumeMounts:
        {{- range .volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- if .volumes }}
      volumes:
      {{- range .volumes }}
      - name: {{ .name }}
        {{- if .configMap }}
        configMap:
          name: {{ .configMap.name }}
          {{- if .configMap.defaultMode }}
          defaultMode: {{ .configMap.defaultMode }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- end }}
{{- end }} 