{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
  - port: {{ .containerPort }}
    targetPort: {{ .hostPort }}
  type: ClusterIP
{{- end }} 