apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: "{{ .Values.replicaCount.server }}"
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: "{{ .Values.ports.server }}"
              name: server-api
          resources:
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
