spring:
  application:
    name: ${SPRING_APPLICATION_NAME:document-service}

  # Database configuration  
  datasource:
    url: jdbc:postgresql://postgres:5432/document_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka/}

# Weaviate configuration
weaviate:
  url: ${WEAVIATE_URL:localhost:8080}

# MinIO configuration
minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
