spring:
  application:
    name: ${SPRING_APPLICATION_NAME:document-service}

  # File upload configuration
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # Database configuration
  datasource:
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/document_db}
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # CORS configuration
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,HEAD
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}

server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Weaviate configuration
weaviate:
  url: ${WEAVIATE_URL:http://localhost:8090}
  class-name: Document

# MinIO configuration
minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:documents}
