name: Build and Push Docker Images

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: [client, eureka, api-gateway, hello-service, document-service]
        arch: [amd64, arm64]
        include:
          - service: client
            context: ./client
            dockerfile: ./client/Dockerfile
          - service: eureka
            context: ./server/eureka
            dockerfile: ./server/eureka/Dockerfile
          - service: api-gateway
            context: ./server/api-gateway
            dockerfile: ./server/api-gateway/Dockerfile
          - service: hello-service
            context: ./server/hello-service
            dockerfile: ./server/hello-service/Dockerfile
          - service: document-service
            context: ./server/document-service
            dockerfile: ./server/document-service/Dockerfile
          - arch: amd64
            runner: ubuntu-latest
            platform: linux/amd64
          - arch: arm64
            runner: ubuntu-latest-arm
            platform: linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ env.REGISTRY }}/aet-devops25/team-sigma/${{ matrix.service }}:latest-${{ matrix.arch }}
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: [client, eureka, api-gateway, hello-service, document-service]

    steps:
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create ${{ env.REGISTRY }}/aet-devops25/team-sigma/${{ matrix.service }}:latest \
            ${{ env.REGISTRY }}/aet-devops25/team-sigma/${{ matrix.service }}:latest-amd64 \
            ${{ env.REGISTRY }}/aet-devops25/team-sigma/${{ matrix.service }}:latest-arm64
          docker manifest push ${{ env.REGISTRY }}/aet-devops25/team-sigma/${{ matrix.service }}:latest
