name: PR Tests

on:
  pull_request:
    branches: [main]

jobs:
  build-client:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build with Bun
        run: bun run build

  build-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        service: [eureka, api-gateway, hello-service]
        include:
          - service: eureka
            working-directory: ./server/eureka
          - service: api-gateway
            working-directory: ./server/api-gateway
          - service: hello-service
            working-directory: ./server/hello-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v4
        with:
          gradle-version: "8.13"

      - name: Build with Gradle
        working-directory: "${{ matrix.working-directory }}"
        run: gradle build
